version: "3.8"
services:

  squid:
    image: <username>/squid
    ports:
      - 8081:3128
    command: ./docker-entrypoint.sh" &&  squid

  icapeg:
    image: <username>/icapeg
    ports:
      - 1344:1344
 
