# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  icap:
    repository: glasswallsolutions/go-icap-server
    tag: v0.5.3
    pullPolicy: IfNotPresent
podAnnotations: {}
application:
  icap:
    env:
      CLOUDAPI_URL: "https://cloudapi-dev.glasswall-icap.com"
    secrets: {}
resources:
  icap:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 500Mi
service:
  icap:
    enabled: true
icapservice:
  name: icap-service
  applabel: adaptation
  replicas:
    min: 2
    max: 150
  port: 1344
  tlsport: 1345
  enableFileId: true
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
scale:
  icap:
    enabled: true
    MinReplicaCount: 1
    MaxReplicaCount: 8
