name: Go

on:
  push:
    branches: [ "restructure" ]
  pull_request:
    branches: [ "restructure" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install c-icap
        go build .

    - name: Run ICAPeg
      run: ./icapeg &


    - name: Test
      run: | 
        chmod +x ./testing/testByHash.sh
        ./testing/testByHash.sh
